services:
  redis:
    container_name: zihuan-redis
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command:
      - redis-server
      - /etc/redis/redis.conf
